package org.showcontrol4j.broker;

import com.hivemq.client.mqtt.MqttClientSslConfig;
import com.hivemq.client.mqtt.mqtt3.Mqtt3Client;
import com.hivemq.client.mqtt.mqtt3.Mqtt3ClientBuilder;

import javax.net.ssl.TrustManagerFactory;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.security.GeneralSecurityException;
import java.security.KeyStore;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;

/**
 * Serves as a wrapper for building {@link Mqtt3Client} MQTT client instances against a configured
 * broker host/port and, optionally, credentials and TLS. Lombok was not used for this class because
 * we need to exclude the stored configuration from a generated constructor and validate it ourselves.
 *
 * @author James Hare
 */
public class BrokerConnectionFactory {

  private final String host;
  private final int port;
  private final String user;
  private final String password;
  private final boolean tlsEnabled;
  private final File trustedCertificate;

  private BrokerConnectionFactory(final Builder builder) {
    host = builder.host;
    port = builder.port;
    user = builder.user;
    password = builder.password;
    tlsEnabled = builder.tlsEnabled;
    trustedCertificate = builder.trustedCertificate;
  }

  /**
   * Builds a new, not-yet-connected {@link Mqtt3Client} for the given client identifier. Callers are
   * responsible for connecting it (via {@code toBlocking().connect()} or {@code toAsync().connect()})
   * before publishing or subscribing.
   *
   * @param clientIdentifier a unique MQTT client identifier for this connection - two simultaneous
   *                          connections to the same broker with the same identifier will conflict.
   * @return a new {@link Mqtt3Client} configured with this factory's broker host/port, credentials,
   *         and TLS settings.
   */
  public Mqtt3Client newConnection(final String clientIdentifier) {
    final Mqtt3ClientBuilder clientBuilder = Mqtt3Client.builder()
            .identifier(clientIdentifier)
            .serverHost(host)
            .serverPort(port);
    if (user != null) {
      clientBuilder.simpleAuth()
              .username(user)
              .password(password.getBytes(StandardCharsets.UTF_8))
              .applySimpleAuth();
    }
    if (tlsEnabled) {
      if (trustedCertificate != null) {
        clientBuilder.sslConfig(sslConfigTrusting(trustedCertificate));
      } else {
        clientBuilder.sslWithDefaultConfig();
      }
    }
    return clientBuilder.build();
  }

  /**
   * Builds an {@link MqttClientSslConfig} that trusts only the given certificate, for connecting to a
   * broker using a self-signed certificate (e.g. the dev-only certificate generated by
   * {@code setup/generate-dev-certs.sh}). A broker with a certificate issued by a publicly trusted CA
   * doesn't need this - use {@link Builder#tls()} instead, which trusts the JVM's default trust store.
   */
  private static MqttClientSslConfig sslConfigTrusting(final File certificateFile) {
    try (final InputStream certificateStream = new FileInputStream(certificateFile)) {
      final CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
      final Certificate certificate = certificateFactory.generateCertificate(certificateStream);

      final KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
      trustStore.load(null, null);
      trustStore.setCertificateEntry("showcontrol4j-broker-ca", certificate);

      final TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
      trustManagerFactory.init(trustStore);

      return MqttClientSslConfig.builder()
              .trustManagerFactory(trustManagerFactory)
              .build();
    } catch (final IOException | GeneralSecurityException e) {
      throw new IllegalArgumentException("Could not load the trusted certificate at " + certificateFile, e);
    }
  }

  /**
   * Serves as a static builder class to build a {@link BrokerConnectionFactory} object.
   */
  public static class Builder {

    private static final int DEFAULT_PORT = 1883;

    private String host;
    private int port = DEFAULT_PORT;
    private String user;
    private String password;
    private boolean tlsEnabled;
    private File trustedCertificate;

    /**
     * Constructor
     */
    public Builder() {
    }

    /**
     * Sets the hostname of the {@link BrokerConnectionFactory}.
     *
     * @param host the hostname of the {@link BrokerConnectionFactory}.
     * @return the Builder object.
     */
    public Builder host(final String host) {
      this.host = host;
      return this;
    }

    /**
     * Sets the port of the {@link BrokerConnectionFactory}. Defaults to 1883, the standard
     * unencrypted MQTT port, if not set - callers enabling TLS will usually want to set this to 8883
     * as well, since enabling TLS does not change the port on its own.
     *
     * @param port the broker port to connect to.
     * @return the Builder object.
     */
    public Builder port(final int port) {
      this.port = port;
      return this;
    }

    /**
     * Sets the credentials used to make a connection to the broker, if necessary.
     *
     * @param user the username used to make a connection to the broker.
     * @param password the password used to make a connection to the broker.
     * @return the Builder object.
     */
    public Builder withCredentials(final String user, final String password) {
      this.user = user;
      this.password = password;
      return this;
    }

    /**
     * Enables TLS, trusting certificates issued by a publicly trusted certificate authority (the
     * JVM's default trust store). Use this against a broker with a real CA-issued certificate.
     *
     * @return the Builder object.
     */
    public Builder tls() {
      this.tlsEnabled = true;
      return this;
    }

    /**
     * Enables TLS, trusting only the given certificate - for a broker using a self-signed
     * certificate, such as the one {@code setup/generate-dev-certs.sh} generates for local
     * development. Never point this at a certificate you don't control.
     *
     * @param trustedCertificate an X.509 certificate file (PEM or DER) to trust.
     * @return the Builder object.
     */
    public Builder tls(final File trustedCertificate) {
      this.tlsEnabled = true;
      this.trustedCertificate = trustedCertificate;
      return this;
    }

    /**
     * Builds the {@link BrokerConnectionFactory} object with the builder.
     *
     * @return the {@link BrokerConnectionFactory} object.
     */
    public BrokerConnectionFactory build() {
      return new BrokerConnectionFactory(this);
    }

  }

}
